name       : perl-module-install
version    : '1.21'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Module-Install-1.21.tar.gz : fbf91007f30565f3920e106055fd0d4287981d5e7dad8b35323ce4b733f15a7b
homepage   : https://metacpan.org/pod/Module::Install
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Module::Install - Standalone, extensible Perl module installer
description: |
    Module::Install is a package for writing installers for CPAN (or CPAN-like) distributions that are clean, simple, minimalist, act in a strictly correct manner with ExtUtils::MakeMaker, and will run on any Perl installation version 5.005 or newer.
builddeps  :
    - perl-file-remove
    - perl-yaml-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
