name       : perl-module-install
version    : 1.19
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Module-Install-1.19.tar.gz : 1a53a78ddf3ab9e3c03fc5e354b436319a944cba4281baf0b904fa932a13011b
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Module::Install - Standalone, extensible Perl module installer
description: |
    Module::Install is a package for writing installers for CPAN (or CPAN-like) distributions that are clean, simple, minimalist, act in a strictly correct manner with ExtUtils::MakeMaker, and will run on any Perl installation version 5.005 or newer.
builddeps  :
    - perl-file-remove
    - perl-yaml-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
